config/routes.rb
PhotoApp::Application.routes.draw do
  root :to => 'home#index'
  resources :users
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :email, :user_name, :password, :on => :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/sessions_controller.rb
class SessionssController < ApplicationController

  def create
    user = User.find_by_email()
    if @user.save
      redirect_to root_path, :notice => "Welcome Aboard!"
    else
      render "new"
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :f_name, :l_name,
      :password, :password_confirmation, :bio, :admin)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_secure_password

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, :notice => "Welcome Aboard!"
    else
      render "new"
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :f_name, :l_name,
      :password, :password_confirmation, :bio, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%body
  #container.top
    %nav
      %tr
        %td
          = link_to 'Sign up', new_user_path
        %td
          = link_to 'Come aboard', login_path
.container_12
  .center_column.grid_6.push_3

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user_name
    = f.text_field :user_name
    %a *
  %br/
  .field
    = f.label :email
    = f.text_field :email
    %a *
  %br/
  .field
    = f.label "First Name"
    = f.text_field :f_name
  %br/
  .field
    = f.label "Last Name"
    = f.text_field :l_name
  %br/
  .field
    = f.label :password
    = f.password_field :password
    %a *
  %br/
  .field
    = f.label :confirmation
    = f.password_field :password_confirmation
    %a *
  .actions
    = f.submit 'Sign Up!'

app/views/users/new.html.haml
%h1 Sign Up!
= render 'form'
= link_to 'Back', root_path